name: Chromium, Firefox

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: bin/setup-rabbit.sh
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npx playwright install --with-deps chromium firefox
      - run: npx playwright test --project=chromium --project=firefox
      - run: npm pack
      - run: bin/rx-stomp.sh
