# This is a basic workflow that is manually triggered

name: NodeJS Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [16, 18, 19]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - run: bin/setup-rabbit.sh
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
      - run: npm i stomp-js/tcp-wrapper --save-dev
      - run: npm run build
      - run: npm run test
      - run: CONN_MODE=tcp npm run test
